openapi: 3.0.0
info:
  title: Exchange Currency API
  description: |-
    This is an API to get and set currency exchange rates
  version: 1.0.11
paths:
  /currency/exchangerate:
    get:
      operationId: CurrencyController_getLatestRatesFromBase
      parameters:
        - name: base
          required: true
          in: query
          schema:
            enum:
              - GBP
              - USD
              - EUR
            type: string
      responses:
        "200":
          description: Return all currency exchange rates
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CurrencyExchangeResponseDto"
    post:
      operationId: CurrencyController_changeCurrencyValue
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CurrencyValueChangeBodyDto"
      responses:
        "200":
          description: Currency value updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    CurrencyExchangeResponseDto:
      type: object
      properties:
        base:
          required: true
          type: string
          example: "USD"
        date:
          required: true
          type: string
          format: date
        rates:
          required: true
          type: object
          additionalProperties:
            type: number
          example: { "USD": 1, "EUR": 0.9, "GBP": 0.8 }
    CurrencyValueChangeBodyDto:
      type: object
      properties:
        currency:
          type: string
          enum:
            - GBP
            - USD
            - EUR
        value:
          type: number
          format: float
      required:
        - currency
        - value
