/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/currency/exchangerate": {
    get: operations["CurrencyController_getLatestRatesFromBase"];
    post: operations["CurrencyController_changeCurrencyValue"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    CurrencyExchangeResponseDto: {
      base: string;
      /** Format: date */
      date: string;
      rates: {
        [key: string]: number;
      };
    };
    CurrencyValueChangeBodyDto: {
      /** @enum {string} */
      currency: "GBP" | "USD" | "EUR";
      /** Format: float */
      value: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  CurrencyController_getLatestRatesFromBase: {
    parameters: {
      query: {
        base: "GBP" | "USD" | "EUR";
      };
    };
    responses: {
      /** @description Return all currency exchange rates */
      200: {
        content: {
          "application/json": components["schemas"]["CurrencyExchangeResponseDto"];
        };
      };
    };
  };
  CurrencyController_changeCurrencyValue: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CurrencyValueChangeBodyDto"];
      };
    };
    responses: {
      /** @description Currency value updated successfully */
      200: {
        content: {
          "application/json": {
            message?: string;
          };
        };
      };
    };
  };
}
