/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/currency/exchangerate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["CurrencyController_getLatestRatesFromBase"];
    put?: never;
    post: operations["CurrencyController_changeCurrencyValue"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CurrencyExchangeResponseDto: {
      base: string;
      /** Format: date */
      date: string;
      rates: {
        [key: string]: number | undefined;
      };
    };
    CurrencyValueChangeBodyDto: {
      /** @enum {string} */
      currency: "GBP" | "USD" | "EUR";
      /** Format: float */
      value: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  CurrencyController_getLatestRatesFromBase: {
    parameters: {
      query: {
        base: "GBP" | "USD" | "EUR";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Return all currency exchange rates */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrencyExchangeResponseDto"];
        };
      };
    };
  };
  CurrencyController_changeCurrencyValue: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CurrencyValueChangeBodyDto"];
      };
    };
    responses: {
      /** @description Currency value updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            message?: string;
          };
        };
      };
    };
  };
}
